### ISSUE TITLE
最新版1.3.2 异常

### ISSUE THREAD

**Issue by senglez** [LinusLing/WeChatMediaPlatformAutomation#11]
更新到1.3.2 后，配置文件没有变化，预览或者发送，都出现异常错误：

`
发生异常，详情请见 ErrorResult.png
TimeoutError: waiting for selector "#app > div.main_bd > div:nth-child(3) > div.weui-desktop-panel__bd > div > div:nth-child(1)" failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/wechat-mp-automation/node_modules/puppeteer/lib/DOMWorld.js:407:34)
    at DOMWorld._waitForSelectorOrXPath (/usr/local/lib/node_modules/wechat-mp-automation/node_modules/puppeteer/lib/DOMWorld.js:332:26)
    at DOMWorld.waitForSelector (/usr/local/lib/node_modules/wechat-mp-automation/node_modules/puppeteer/lib/DOMWorld.js:315:21)
    at Frame.waitForSelector (/usr/local/lib/node_modules/wechat-mp-automation/node_modules/puppeteer/lib/FrameManager.js:384:51)
    at Frame.<anonymous> (/usr/local/lib/node_modules/wechat-mp-automation/node_modules/puppeteer/lib/helper.js:117:27)
    at Page.waitForSelector (/usr/local/lib/node_modules/wechat-mp-automation/node_modules/puppeteer/lib/Page.js:867:33)
    at /usr/local/lib/node_modules/wechat-mp-automation/automation.js:224:26 {
  name: 'TimeoutError'
}
`

**Comment by LinusLing** [comment]
我这边没有复现这个问题

**Comment by leoleoasd** [comment]
同
```
